### ISSUE TITLE
dm

### ISSUE THREAD

**Issue by kmchord9** [kmchord9/raspi-datapost#2]
$ python datapost.py 
Traceback (most recent call last):
  File "datapost.py", line 5, in <module>
    from sensor_module.BME280 import *
  File "/home/pirate/work/raspi-datapost/sensor_module/BME280.py", line 3, in <module>
    from smbus2 import SMBus
ModuleNotFoundError: No module named 'smbus2'

**Comment by kmchord9** [comment]
pip install smbus2
