### ISSUE TITLE
 '/dev/i2c-1'のディレクトリがない

### ISSUE THREAD

**Issue by kmchord9** [kmchord9/raspi-datapost#3]
$ python datapost.py 
Traceback (most recent call last):
  File "datapost.py", line 5, in <module>
    from sensor_module.BME280 import *
  File "/home/pirate/work/raspi-datapost/sensor_module/BME280.py", line 9, in <module>
    bus = SMBus(bus_number)
  File "/home/pirate/.anyenv/envs/pyenv/versions/datapost/lib/python3.6/site-packages/smbus2/smbus2.py", line 279, in __init__
    self.open(bus)
  File "/home/pirate/.anyenv/envs/pyenv/versions/datapost/lib/python3.6/site-packages/smbus2/smbus2.py", line 308, in open
    self.fd = os.open(filepath, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/i2c-1'

**Comment by kmchord9** [comment]
sudo raspi-configでspiを有効にする
